# This file controls the configuration for the "Dependabot" service, used to keep dependencies updated.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# See the above link for the reason why "directory" is set to "/"
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Ignore foundry-vtt-types - deliberately kept at v9 to avoid breaking changes
    # Upgrading to v13 causes 24+ TypeScript errors. See commit 66dbe71 and .npmrc.
    ignore:
      - dependency-name: "@league-of-foundry-developers/foundry-vtt-types"
        update-types: ["version-update:semver-major"]